server:
  port: 8886


spring:
  application:
    name: rainbow-search

  #注册nacos
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.105.134:8848

  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-cluster

  #admin 客户端配置
  boot:
    admin:
      client:
        url: http://localhost:8887
        username: rainbow
        password: 123456
        instance:
          prefer-ip: true
#配置了SBA客户端的名称，描述和版本信息；
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

# * 表示将SBA客户端的所有监控端点都暴露给SBA服务端；
management:
  endpoints:
    web:
      exposure:
        include: '*'
    #表示总是展示详细的健康信息。
  endpoint:
    health:
      show-details: ALWAYS

# 为了让feign获得token
hystrix:
  shareSecurityContext: true

# 客户端的每一次请求都会去认证服务器校验token
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8882/auth/user


#自定义配置
rainbow:
  cloud:
    security:
      # 免认证url 多个逗号拼接
      anonUris: /actuator/**,/captcha,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/menu/download
      # 是否开启禁止请求绕过网关
      enable: false